### ISSUE TITLE
NVD 업데이트 오류 Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1

### ISSUE THREAD

**Issue by vampard** [fosslight/fosslight#1062]
안녕하세요 NVD 업데이트 중인데, 

schedule.log에서 아래와 같은 에러가 발생하며 동작을 하지 않는 것 같습니다. 

**Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1**

캐릭터셋과 연관이 있어 보여지는데 혹시 어떻게 해결하는지 아시면 답변부탁드립니다. 

사용버전은 1.6.3입니다. 
 - /src/main/java/oss/fosslight/service/NvdDataService.java  코드는 API 제한으로 인해 변경된 2000 값을 500으로 수정하여 2.0.1prelease와 코드가 동일합니다. 

DB 자체 캐릭터셋 
MariaDB [fosslight]> show variables like 'c%';
+----------------------------------+----------------------------+
| Variable_name                    | Value                      |
+----------------------------------+----------------------------+
| character_set_client             | utf8mb3                    |
| character_set_connection         | utf8mb3                    |
| character_set_database           | **utf8mb4**                    |
| character_set_filesystem         | binary                     |
| character_set_results            | utf8mb3                    |
| character_set_server             | utf8mb4                    |
| character_set_system             | utf8mb3                    |
| character_sets_dir               | /usr/share/mysql/charsets/ |

schedule.log 로그
--

2024-08-06 15:54:49.303 20375295 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():241] - nvdCveDataApiJob start
2024-08-06 15:54:58.529 20384521 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 0 / totalResults : 6191
2024-08-06 15:56:32.709 20478701 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 2000 / totalResults : 6191
2024-08-06 15:57:24.189 20530181 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 4000 / totalResults : 6191
2024-08-06 15:57:32.819 20538811 [taskScheduler-1] ERROR [NvdDataService.java, nvdCveDataApiJob():410] - 
### Cause: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy149.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy207.insertCveInfoV3(Unknown Source)
	at oss.fosslight.service.NvdDataService.nvdCveDataApiJob(NvdDataService.java:367)
	at oss.fosslight.service.NvdDataService.executeNvdDataSync(NvdDataService.java:197)
	at oss.fosslight.service.NvdDataService$$FastClassBySpringCGLIB$$82d1f328.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at oss.fosslight.service.NvdDataService$$EnhancerBySpringCGLIB$$7c601214.executeNvdDataSync(<generated>)
	at oss.fosslight.scheduler.SchedulerWorkerTask.nvdDataIfJob(SchedulerWorkerTask.java:80)
	at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at jdk.internal.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy170.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at jdk.internal.reflect.GeneratedMethodAccessor227.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 27 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:175)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 46 common frames omitted
Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1681)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1543)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1506)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:316)
	... 47 common frames omitted
2024-08-06 15:57:32.819 20538811 [taskScheduler-1] INFO  [NvdDataService.java, executeNvdDataSync():201] - nvd meta api connection error
2024-08-06 15:57:32.819 20538811 [taskScheduler-1] ERROR [SchedulerWorkerTask.java, nvdDataIfJob():86] - executeNvdDataSync - resCd : 91
2024-08-06 15:58:26.945 20592937 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():574] - nvdMetaDataApiJob start
2024-08-06 15:58:26.945 20592937 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 0 / totalResults : 5404
2024-08-06 15:58:43.273 20609265 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 500 / totalResults : 5404
2024-08-06 15:58:58.405 20624397 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 1000 / totalResults : 5404
2024-08-06 15:59:17.090 20643082 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 1500 / totalResults : 5404
2024-08-06 15:59:28.605 20654597 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 2000 / totalResults : 5404
2024-08-06 15:59:42.359 20668351 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 2500 / totalResults : 5404
2024-08-06 16:00:03.227 20689219 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 3000 / totalResults : 5404
2024-08-06 16:00:42.025 20728017 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 3500 / totalResults : 5404
2024-08-06 16:00:58.603 20744595 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 4000 / totalResults : 5404
2024-08-06 16:01:09.638 20755630 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 4500 / totalResults : 5404
2024-08-06 16:01:32.130 20778122 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 5000 / totalResults : 5404
2024-08-06 16:02:02.466 20808458 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():726] - httpsUrlConnectionFlag : true
2024-08-06 16:02:48.533 20854525 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():745] - nvdMetaDataApiJob end
2024-08-06 16:02:55.373 20861365 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():241] - nvdCveDataApiJob start
2024-08-06 16:03:05.431 20871423 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 0 / totalResults : 6191
2024-08-06 16:04:37.075 20963067 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 2000 / totalResults : 6191
2024-08-06 16:05:30.783 21016775 [taskScheduler-1] INFO  [NvdDataService.java, nvdCveDataApiJob():251] - nvdCveData index : 4000 / totalResults : 6191
2024-08-06 16:05:38.196 21024188 [taskScheduler-1] ERROR [NvdDataService.java, nvdCveDataApiJob():410] - 
### Cause: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy149.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy207.insertCveInfoV3(Unknown Source)
	at oss.fosslight.service.NvdDataService.nvdCveDataApiJob(NvdDataService.java:367)
	at oss.fosslight.service.NvdDataService.executeNvdDataSync(NvdDataService.java:197)
	at oss.fosslight.service.NvdDataService$$FastClassBySpringCGLIB$$82d1f328.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at oss.fosslight.service.NvdDataService$$EnhancerBySpringCGLIB$$7c601214.executeNvdDataSync(<generated>)
	at oss.fosslight.scheduler.SchedulerWorkerTask.nvdDataIfJob(SchedulerWorkerTask.java:80)
	at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: (conn=150895) Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at jdk.internal.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy170.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at jdk.internal.reflect.GeneratedMethodAccessor227.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 27 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:175)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 46 common frames omitted
Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x93\xB7_T...' for column `fosslight`.`NVD_CVE_V3`.`VULN_SUMMARY` at row 1
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1681)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1543)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1506)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:316)
	... 47 common frames omitted

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Environment (please complete the following information):**
 - Etc

**Additional context**

**Comment by vampard** [comment]
insert되는 데이터에 이모지가 포함되어 에러가 발생했네요.

NVD_CVE_V3 테이블의 캐릭터셋이 utf8mb3였는데, 아래와 같이 utf8mb4로 변경해주니 에러가 사라졌습니다. 

alter table NVD_CVE_V3 convert to character set utf8mb4 collate utf8mb4_general_ci;

**Comment by hyeinlee00** [comment]
@vampard 확인 감사합니다! 가능하시다면 수정내용 develop 브랜치로 PR올려주시면 기여해주시면 반영하도록 하겠습니다.

혹시 반영이 어려우시다면, 2.0.0 정식버전에는 말씀하신 내용 반영될 수 있도록 하려고 합니다. 의견 말씀해주세요 :)

**Comment by vampard** [comment]
develop 브랜치에서 다시 pull request로 해당 버전 수정해달라고 요청해달라는 말씀이신거죠?

**Comment by hyeinlee00** [comment]
넵 repository를 Fork하신 후 develop 브랜치 기준으로 수정하고 pull request요청해주시면 기여 가능합니다 :)

또한 현재 develop은 2.x로 버전이 올라갔기 떄문에,
1.6.3에서 known issue로 알고 있던 내용들을 1.6.4 브랜치에서 수정해서 관리하려고 하고있습니다.

이 이슈는 1.6.4와 develop 모두 반영되면 좋을 것 같아서, 양쪽에 PR을 주셔도 좋을 것 같습니다!

상세한 기여가이드는 아래 페이지 참고 부탁드립니다:
https://fosslight.org/hub-guide/contribution/1_contribution.html

**Comment by vampard** [comment]
네 알겠습니다. 기여 후 코멘트 남기도록 하겠습니다.

**Comment by hyeinlee00** [comment]
@vampard 님 해당 이슈 character set바꾸는 PR로 수정된 것으로 보입니다.
맞다면 이슈 close하고자 하는데 확인차 답변 부탁드립니다 :)

**Comment by vampard** [comment]
네 제가 PR요청드렸고 커밋되었네요. 클로즈 부탁드립니다.

**Comment by hyeinlee00** [comment]
네 확인 감사합니다! 그리고 기여 해주셔서 감사합니다 :) 👍
