### ISSUE TITLE
Vulnerability > NVD Batch Job - Not working

### ISSUE THREAD

**Issue by kwmyoo** [fosslight/fosslight#16]
Fosslight 가이드에 보면 vulnerability check을 위해 NVD에서 매일 data feed를 받아와 저장한다고 되어 있습니다.

하지만 Fosslight를 직접 설치하여 사용해본 결과 그 기능이 작동하지 않는 것 같습니다.

예를 들어, vulnerability에 tomcat 검색해봐도 뜨지 않습니다.

**Comment by kwmyoo** [comment]
로그파일을 요청하셔서 올려드립니다. 가장 최근 로그파일이고, backup 디렉토리의 다른 로그가 필요하다면 다시 말씀해주세요.
[fosslight.log](https://github.com/fosslight/fosslight/files/6907576/fosslight.log)

**Comment by soimkim** [comment]
Error : 
- NVD Sync (Cron job) does not work, so nothing is searched in the list of vulnerability list.

Error Message: 
```
ERROR [NvdDataService.java, executeNvdDataSync():64] - /data/fosslight/nvd/cve/nvdcpematch-1.0.json.zip (No such file or directory)
java.io.FileNotFoundException: /data/fosslight/nvd/cve/nvdcpematch-1.0.json.zip (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at oss.fosslight.util.FileUtil.downloadFile(FileUtil.java:325)
	at oss.fosslight.service.NvdDataService.nvdFeedDataDownloadJob(NvdDataService.java:437)
	at oss.fosslight.service.NvdDataService.executeNvdDataSync(NvdDataService.java:60)
	at oss.fosslight.scheduler.SchedulerWorkerTask.nvdDataIfJob(SchedulerWorkerTask.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-07-31 08:30:02.747 129944 [taskScheduler-1] ERROR [SchedulerWorkerTask.java, nvdDataIfJob():99] - executeNvdDataSync - resCd : 91
^C
```

**Comment by soimkim** [comment]
@kwmyoo , 하기와 같이 DB 세팅 값을 변경 후 결과 공유 부탁드립니다. 
NVD 배치 작업은 1시에 시작되도록 되어 있습니다. 그 이후 결과 공유 부탁드립니다.

Please share the NVD batch results after changing the DB setting values as shown below.
NVD batch jobs are supposed to start at 1:00.

``` SET GLOBAL max_allowed_packet=1073741824; ``` 

Ref. https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size

**Comment by kwmyoo** [comment]
답변 주신대로 수정하였지만 (아래 사진 참고) 여전히 NVD 데이터는 안 들어오고 있습니다.
![image](https://user-images.githubusercontent.com/38739929/128274787-0a52a82a-f6e0-4796-90e4-d8f6d93abc98.png)

**Comment by soimkim** [comment]
@kwmyoo , log 파일 공유 부탁드립니다. 
schedule.log와 fosslight.log, fosslight_err.log 첨부 부탁드립니다.

**Comment by kwmyoo** [comment]
schedule.log 파일은 찾지 못하였습니다. 
[fosslight_err.log](https://github.com/fosslight/fosslight/files/6935676/fosslight_err.log)
[fosslight.log](https://github.com/fosslight/fosslight/files/6935677/fosslight.log)

그리고, 덧붙혀서 말씀드리자면 
[nvdcve-1.1-modified.json.zip](https://github.com/fosslight/fosslight/files/6935684/nvdcve-1.1-modified.json.zip)
[nvdcpematch-1.0.json.zip](https://github.com/fosslight/fosslight/files/6935685/nvdcpematch-1.0.json.zip)
이 두개가 fosslight/web-data/nvd/cve 디렉토리에 있는 것을 확인하였습니다.

**Comment by soimkim** [comment]
Error : 
```
ERROR 21-08-04 01:01:43[taskScheduler-1] [o.f.s.vulnerability.NvdDataService:53] - 
### Error updating database.  Cause: java.sql.SQLTransientConnectionException: (conn=9655) Could not send query: query size is >= to max_allowed_packet (16777216)
### The error may involve defaultParameterMap
### The error occurred while setting parameters

...
### Cause: java.sql.SQLTransientConnectionException: (conn=9655) Could not send query: query size is >= to max_allowed_packet (16777216)
; (conn=9655) Could not send query: query size is >= to max_allowed_packet (16777216); nested exception is java.sql.SQLTransientConnectionException: (conn=9655) Could not send query: query size is >= to max_allowed_packet (16777216)
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy158.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy205.insertBulkCpeMatchNameData(Unknown Source)
	at oss.fosslight.service.vulnerability.NvdDataService.nvdMetaDataSyncJob(NvdDataService.java:516)
	at oss.fosslight.service.vulnerability.NvdDataService.executeNvdDataSync(NvdDataService.java:50)
	at oss.fosslight.service.vulnerability.NvdDataService$$FastClassBySpringCGLIB$$f1716f1a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at oss.fosslight.service.vulnerability.NvdDataService$$EnhancerBySpringCGLIB$$4daecbec.executeNvdDataSync(<generated>)
	at oss.fosslight.scheduler.SchedulerWorkerTask.nvdDataIfJob(SchedulerWorkerTask.java:77)
	at sun.reflect.GeneratedMethodAccessor1708.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: (conn=9655) Could not send query: query size is >= to max_allowed_packet (16777216)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.GeneratedMethodAccessor369.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 25 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Could not send query: query size is >= to max_allowed_packet (16777216)
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:175)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 39 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: Could not send query: query size is >= to max_allowed_packet (16777216)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:2049)
	... 41 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream.flushBuffer(StandardPacketOutputStream.java:111)
	at org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream.flush(AbstractPacketOutputStream.java:186)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:314)
	... 40 common frames omitted
ERROR 21-08-04 01:01:44[taskScheduler-1] [o.f.scheduler.SchedulerWorkerTask:83] - executeNvdDataSync - resCd : 91

```

**Comment by soimkim** [comment]
@kwmyoo 님, 에러 로그는 max_allowed_packet  값이 바뀌지않은 것으로 보입니다. 
혹시 SET GLOBAL max_allowed_packet=1073741824;  세팅 후 db 서비스를 restart 하셨는 지 문의드립니다.

**Comment by kwmyoo** [comment]
해결됐습니다.
