### ISSUE TITLE
statistics menu - An error occurred on updated oss, updated license

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#743]
**Describe the bug**
An error is occurring in statistics.
There were errors in three areas: Divisional Project, Updated OSS, and Updated License
The Divisional Project was caused by an issue where the newly added Divison was not filled with the default value when upgrading the FOSSLight version
We solved it by filling the Divison with the default value, but we don't know which part of the other 2 statistics is the problem

**To Reproduce**
v1.2.28 -> v.1.4.8 upgrade

**Screenshots**
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/60166229/199371476-fe0b55bf-c146-4d40-a52f-4b140b73543a.png">

**Comment by dongs0** [comment]
@dongs0, statistics 화면에 접속할때 확인해보니 에러팝업은 계속 뜨는데 error log가 찍히지는 않습니다.
우선 가장 가까운 시간에 찍힌 에러 로그 공유 드립니다.

-------------------
ERROR 22-11-08 20:03:12[http-nio-8180-exec-6] [o.a.c.c.C.[.[.[.[dispatcherServlet]:175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe; nested exception is com.google.gson.JsonIOException: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe] with root cause
java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
~ (이후 java 관련 메시지들)

**Comment by soimkim** [comment]
@dongs0 님, 로그 일부분으로는 확인이 어렵습니다. 로그 파일 업로드 부탁드립니다.

**Comment by dongs0** [comment]
@soimkim 님 말씀드린것처럼 에러 팝업과 함께 발생하는 로그는 찍히는게 없고 공유 드린 로그 외에는 특별한 내용이 없습니다..
로그 파일 첨부 드립니다!
[fosslight_error.txt](https://github.com/fosslight/fosslight/files/9969018/fosslight_error.txt)
